package interface_bd.Usuario;

import interface_bd.Login.Login;
import interface_bd.Login.ERRO; // Importa a classe ERRO
import java.awt.Dimension;
import java.io.IOException;
import java.util.List;
import java.util.ArrayList;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.DefaultComboBoxModel; // Para inicializar os ComboBoxes

/**
 *
 * @author Usuario
 */
public class Usuario extends javax.swing.JFrame {

    private static Usuario instance;

    private Dimension minimumSize;
    private Dimension preferredSize;

    /**
     * Creates new form Login
     */
    private Usuario() {
        initComponents();
        this.setLocationRelativeTo(null);
        initializeComboBoxes(); // Inicializa os ComboBoxes com opções
        addListeners(); // Adiciona os listeners para os botões
    }

    public static Usuario getInstance() {
        if (instance == null) { // Se a instância ainda não existe, crie-a
            instance = new Usuario();
        }
        return instance; // Retorne a instância existente (ou a recém-criada)
    }

    // Método para inicializar os ComboBoxes com opções
    private void initializeComboBoxes() {
        // Opções para CB_Nota
        String[] notas = {"1", "2", "3", "4", "5"};
        CB_Nota.setModel(new DefaultComboBoxModel<>(notas));
        CB_Nota.setSelectedItem("3"); // Define um valor padrão

        // Opções para CB_Status
        String[] status = {"Lido", "Lendo", "Quero Ler"};
        CB_Status.setModel(new DefaultComboBoxModel<>(status));
        CB_Status.setSelectedItem("Quero Ler"); // Define um valor padrão
    }

    // Método para adicionar listeners aos botões
    private void addListeners() {
        B_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_SairActionPerformed(evt);
            }
        });

        B_Adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_AdicionarActionPerformed(evt);
            }
        });

        B_Livros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_LivrosActionPerformed(evt);
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // TODO add your handling code here:
    // TODO add your handling code here:
    // </editor-fold>//GEN-END:initComponents
    // TODO add your handling code here:
    // TODO add your handling code here:
    // </editor-fold>//GEN-END:initComponents



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Usuario.getInstance().setVisible(true);
            }
        });
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PaUsuario = new javax.swing.JPanel();
        T_titulo = new javax.swing.JTextField();
        Titulo = new java.awt.Label();
        TB_Usuario = new javax.swing.JToolBar();
        L_Usuario = new java.awt.Label();
        B_Sair = new java.awt.Button();
        B_Adicionar = new java.awt.Button();
        Autor = new java.awt.Label();
        T_Autor = new javax.swing.JTextField();
        Status = new java.awt.Label();
        Genero = new java.awt.Label();
        Comentario = new java.awt.Label();
        Sinopse = new java.awt.Label();
        Nota = new java.awt.Label();
        CB_Status = new javax.swing.JComboBox<>();
        SP_Sinopse = new javax.swing.JScrollPane();
        TA_Sinopse = new javax.swing.JTextArea();
        SP_Comentario = new javax.swing.JScrollPane();
        TA_Comentario = new javax.swing.JTextArea();
        CB_Nota = new javax.swing.JComboBox<>();
        SP_Genero = new javax.swing.JScrollPane();
        L_Genero = new javax.swing.JList<>();
        B_Livros = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Usuario");
        setBackground(new java.awt.Color(220, 220, 220));
        setMinimumSize(this.preferredSize);
        setResizable(false);

        PaUsuario.setBackground(new java.awt.Color(220, 220, 220));
        PaUsuario.setForeground(new java.awt.Color(0, 0, 0));
        PaUsuario.setMaximumSize(this.minimumSize);
        PaUsuario.setMinimumSize(this.preferredSize);

        T_titulo.setBackground(new java.awt.Color(230, 230, 230));
        T_titulo.setForeground(new java.awt.Color(30, 30, 30));
        T_titulo.setCaretColor(new java.awt.Color(0, 0, 0));
        T_titulo.setDisabledTextColor(new java.awt.Color(120, 120, 120));
        T_titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_tituloActionPerformed(evt);
            }
        });

        Titulo.setAlignment(java.awt.Label.CENTER);
        Titulo.setBackground(new java.awt.Color(230, 230, 230));
        Titulo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Titulo.setForeground(new java.awt.Color(60, 60, 60));
        Titulo.setMinimumSize(new java.awt.Dimension(50, 50));
        Titulo.setText("Titulo:");

        TB_Usuario.setBackground(new java.awt.Color(210, 210, 210));
        TB_Usuario.setRollover(true);

        L_Usuario.setAlignment(java.awt.Label.CENTER);
        L_Usuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        L_Usuario.setForeground(new java.awt.Color(60, 60, 60));
        L_Usuario.setMinimumSize(new java.awt.Dimension(100, 100));
        L_Usuario.setName("L_Usuario"); // NOI18N
        L_Usuario.setText("Usuario");
        TB_Usuario.add(L_Usuario);

        B_Sair.setActionCommand("Sair");
        B_Sair.setLabel("Sair");
        B_Sair.setName("Sair"); // NOI18N
        B_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_SairActionPerformed(evt);
            }
        });

        B_Adicionar.setActionCommand("Registra");
        B_Adicionar.setLabel("Adicionar");
        B_Adicionar.setName("Adicionar"); // NOI18N
        B_Adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_AdicionarActionPerformed(evt);
            }
        });

        Autor.setAlignment(java.awt.Label.CENTER);
        Autor.setBackground(new java.awt.Color(230, 230, 230));
        Autor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Autor.setForeground(new java.awt.Color(60, 60, 60));
        Autor.setMinimumSize(new java.awt.Dimension(50, 50));
        Autor.setText("Autor:");

        T_Autor.setBackground(new java.awt.Color(230, 230, 230));
        T_Autor.setForeground(new java.awt.Color(30, 30, 30));
        T_Autor.setCaretColor(new java.awt.Color(0, 0, 0));
        T_Autor.setDisabledTextColor(new java.awt.Color(120, 120, 120));
        T_Autor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_AutorActionPerformed(evt);
            }
        });

        Status.setAlignment(java.awt.Label.CENTER);
        Status.setBackground(new java.awt.Color(230, 230, 230));
        Status.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Status.setForeground(new java.awt.Color(60, 60, 60));
        Status.setMinimumSize(new java.awt.Dimension(50, 50));
        Status.setText("Status:");

        Genero.setAlignment(java.awt.Label.CENTER);
        Genero.setBackground(new java.awt.Color(230, 230, 230));
        Genero.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Genero.setForeground(new java.awt.Color(60, 60, 60));
        Genero.setMinimumSize(new java.awt.Dimension(50, 50));
        Genero.setText("Genero:");

        Comentario.setAlignment(java.awt.Label.CENTER);
        Comentario.setBackground(new java.awt.Color(230, 230, 230));
        Comentario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Comentario.setForeground(new java.awt.Color(60, 60, 60));
        Comentario.setMinimumSize(new java.awt.Dimension(50, 50));
        Comentario.setText("Comentario:");

        Sinopse.setAlignment(java.awt.Label.CENTER);
        Sinopse.setBackground(new java.awt.Color(230, 230, 230));
        Sinopse.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Sinopse.setForeground(new java.awt.Color(60, 60, 60));
        Sinopse.setMinimumSize(new java.awt.Dimension(50, 50));
        Sinopse.setText("Sinopse:");

        Nota.setAlignment(java.awt.Label.CENTER);
        Nota.setBackground(new java.awt.Color(230, 230, 230));
        Nota.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Nota.setForeground(new java.awt.Color(60, 60, 60));
        Nota.setMinimumSize(new java.awt.Dimension(50, 50));
        Nota.setText("Nota:");

        CB_Status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lido", "Lendo", "Ver", "Pausado" }));
        CB_Status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_StatusActionPerformed(evt);
            }
        });

        SP_Sinopse.setMaximumSize(this.minimumSize);
        SP_Sinopse.setMinimumSize(this.preferredSize);
        SP_Sinopse.setPreferredSize(new java.awt.Dimension(173, 86));
        SP_Sinopse.setViewportView(TA_Sinopse);

        TA_Sinopse.setLineWrap(true);
        TA_Sinopse.setWrapStyleWord(true);
        TA_Sinopse.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TA_Sinopse.setMaximumSize(new java.awt.Dimension(Integer.MAX_VALUE, Integer.MAX_VALUE));
        TA_Sinopse.setMinimumSize(new java.awt.Dimension(Integer.MIN_VALUE, Integer.MIN_VALUE));
        SP_Sinopse.setViewportView(TA_Sinopse);

        SP_Comentario.setMaximumSize(this.minimumSize);
        SP_Comentario.setMinimumSize(this.preferredSize);
        SP_Comentario.setPreferredSize(new java.awt.Dimension(173, 86));
        SP_Comentario.setViewportView(TA_Comentario);

        TA_Comentario.setLineWrap(true);
        TA_Comentario.setWrapStyleWord(true);
        TA_Comentario.setMaximumSize(new java.awt.Dimension(Integer.MAX_VALUE, Integer.MAX_VALUE));
        TA_Comentario.setMinimumSize(new java.awt.Dimension(Integer.MIN_VALUE, Integer.MIN_VALUE));
        SP_Comentario.setViewportView(TA_Comentario);

        CB_Nota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));
        CB_Nota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_NotaActionPerformed(evt);
            }
        });

        SP_Genero.setToolTipText("");
        SP_Genero.setMaximumSize(this.minimumSize);
        SP_Genero.setMinimumSize(this.preferredSize);
        SP_Genero.setPreferredSize(new java.awt.Dimension(164, 82));

        L_Genero.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "ROMANCE", "ACAO", "TERROR", "SUSPENSE", "FANTASIA", "+18", "ESCOLAR", "SOBRENATURAL", "DIDATICO", "FILOSOFIA", "MATEMATICA", "SOCIOLOGIA", "INFANTIL" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        L_Genero.setMaximumSize(new java.awt.Dimension(Integer.MAX_VALUE, Integer.MAX_VALUE));
        L_Genero.setMinimumSize(new java.awt.Dimension(Integer.MIN_VALUE, Integer.MIN_VALUE));
        SP_Genero.setViewportView(L_Genero);

        B_Livros.setActionCommand("Sair");
        B_Livros.setLabel("Livros");
        B_Livros.setName("Livros"); // NOI18N
        B_Livros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_LivrosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PaUsuarioLayout = new javax.swing.GroupLayout(PaUsuario);
        PaUsuario.setLayout(PaUsuarioLayout);
        PaUsuarioLayout.setHorizontalGroup(
            PaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TB_Usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PaUsuarioLayout.createSequentialGroup()
                .addComponent(B_Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(PaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PaUsuarioLayout.createSequentialGroup()
                        .addGroup(PaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(SP_Sinopse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(SP_Comentario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(PaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PaUsuarioLayout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addGroup(PaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Nota, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Status, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Comentario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(CB_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CB_Nota, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PaUsuarioLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(SP_Genero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(13, 13, 13))
                    .addGroup(PaUsuarioLayout.createSequentialGroup()
                        .addGroup(PaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PaUsuarioLayout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(Genero, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(T_titulo)
                                .addGroup(PaUsuarioLayout.createSequentialGroup()
                                    .addGap(53, 53, 53)
                                    .addGroup(PaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Autor, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(T_Autor, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(B_Livros, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PaUsuarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PaUsuarioLayout.createSequentialGroup()
                        .addComponent(Sinopse, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PaUsuarioLayout.createSequentialGroup()
                        .addComponent(B_Adicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124))))
        );
        PaUsuarioLayout.setVerticalGroup(
            PaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaUsuarioLayout.createSequentialGroup()
                .addComponent(TB_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PaUsuarioLayout.createSequentialGroup()
                        .addComponent(B_Sair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PaUsuarioLayout.createSequentialGroup()
                        .addGroup(PaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PaUsuarioLayout.createSequentialGroup()
                                .addComponent(B_Livros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PaUsuarioLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(T_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Autor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(T_Autor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(Genero, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SP_Genero, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Status, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CB_Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Nota, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CB_Nota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Comentario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SP_Comentario, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Sinopse, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SP_Sinopse, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                .addGap(9, 9, 9)
                                .addComponent(B_Adicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PaUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PaUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_SairActionPerformed
  
    }//GEN-LAST:event_B_SairActionPerformed


    private void T_tituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_tituloActionPerformed
        
    }//GEN-LAST:event_T_tituloActionPerformed

    private void T_AutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_AutorActionPerformed
        
    }//GEN-LAST:event_T_AutorActionPerformed

    private void CB_StatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_StatusActionPerformed
        
    }//GEN-LAST:event_CB_StatusActionPerformed

    private void CB_NotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_NotaActionPerformed
       
    }//GEN-LAST:event_CB_NotaActionPerformed

    private void B_LivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_LivrosActionPerformed

    }//GEN-LAST:event_B_LivrosActionPerformed

    private void B_AdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_AdicionarActionPerformed
 
    }//GEN-LAST:event_B_AdicionarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label Autor;
    private java.awt.Button B_Adicionar;
    private java.awt.Button B_Livros;
    private java.awt.Button B_Sair;
    private javax.swing.JComboBox<String> CB_Nota;
    private javax.swing.JComboBox<String> CB_Status;
    private java.awt.Label Comentario;
    private java.awt.Label Genero;
    private javax.swing.JList<String> L_Genero;
    private java.awt.Label L_Usuario;
    private java.awt.Label Nota;
    private javax.swing.JPanel PaUsuario;
    private javax.swing.JScrollPane SP_Comentario;
    private javax.swing.JScrollPane SP_Genero;
    private javax.swing.JScrollPane SP_Sinopse;
    private java.awt.Label Sinopse;
    private java.awt.Label Status;
    private javax.swing.JTextArea TA_Comentario;
    private javax.swing.JTextArea TA_Sinopse;
    private javax.swing.JToolBar TB_Usuario;
    private javax.swing.JTextField T_Autor;
    private javax.swing.JTextField T_titulo;
    private java.awt.Label Titulo;
    // End of variables declaration//GEN-END:variables
}
