package interface_bd.Login;

import interface_bd.Registro.Registro;
import interface_bd.ADMIN.ADMIN;
import interface_bd.Usuario.Usuario;
import interface_bd.api.ApiService;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException; // Necessário para tratar exceções de IO

/**
 *
 * @author Usuario
 */
public class Login extends javax.swing.JFrame {

    private static Login instance;
    private Dimension minimumSize;
    private Dimension preferredSize;

    private Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        addRegistrarMouseListener(); // Adiciona o listener para o "Registra"
        addLoginButtonListener();    // Adiciona o listener para o botão de Login
    }

    public static Login getInstance() {
        if (instance == null) {
            instance = new Login();
        }
        return instance;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // </editor-fold>//GEN-END:initComponents
// </editor-fold>//GEN-END:initComponents


    private void LL_SenhaActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }
    // TODO add your handling code here:


    // Método para adicionar o MouseListener ao JLabel "Registra"
    private void addRegistrarMouseListener() {
        Registra.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                // Esconde a tela de Login e abre a de Registro
                setVisible(false);
                Registro.getInstance().setVisible(true);
            }
        });
    }

    // Método para adicionar o ActionListener ao botão B_login
    private void addLoginButtonListener() {
        B_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_loginActionPerformed(evt);
            }
        });
    }
    // Lógica do botão de Login

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PaLogin = new javax.swing.JPanel();
        LL_Senha = new javax.swing.JPasswordField();
        TL_Usuario = new javax.swing.JTextField();
        LL_Usuario = new java.awt.Label();
        Senha = new java.awt.Label();
        jToolBar1 = new javax.swing.JToolBar();
        La_login = new java.awt.Label();
        B_login = new java.awt.Button();
        Registra = new javax.swing.JLabel();
        Esqueci_Senha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBackground(new java.awt.Color(220, 220, 220));
        setMinimumSize(this.preferredSize);
        setResizable(false);

        PaLogin.setBackground(new java.awt.Color(220, 220, 220));
        PaLogin.setForeground(new java.awt.Color(0, 0, 0));
        PaLogin.setMaximumSize(this.minimumSize);
        PaLogin.setMinimumSize(this.preferredSize);

        LL_Senha.setBackground(new java.awt.Color(230, 230, 230));
        LL_Senha.setForeground(new java.awt.Color(30, 30, 30));
        LL_Senha.setCaretColor(new java.awt.Color(0, 0, 0));
        LL_Senha.setDisabledTextColor(new java.awt.Color(120, 120, 120));

        TL_Usuario.setBackground(new java.awt.Color(230, 230, 230));
        TL_Usuario.setForeground(new java.awt.Color(30, 30, 30));
        TL_Usuario.setCaretColor(new java.awt.Color(0, 0, 0));
        TL_Usuario.setDisabledTextColor(new java.awt.Color(120, 120, 120));
        TL_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TL_UsuarioActionPerformed(evt);
            }
        });

        LL_Usuario.setAlignment(java.awt.Label.CENTER);
        LL_Usuario.setBackground(new java.awt.Color(230, 230, 230));
        LL_Usuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        LL_Usuario.setForeground(new java.awt.Color(60, 60, 60));
        LL_Usuario.setMinimumSize(new java.awt.Dimension(50, 50));
        LL_Usuario.setText("Usuario:");

        Senha.setAlignment(java.awt.Label.CENTER);
        Senha.setBackground(new java.awt.Color(230, 230, 230));
        Senha.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Senha.setForeground(new java.awt.Color(60, 60, 60));
        Senha.setMinimumSize(new java.awt.Dimension(50, 50));
        Senha.setText("Senha:");

        jToolBar1.setBackground(new java.awt.Color(210, 210, 210));
        jToolBar1.setRollover(true);

        La_login.setAlignment(java.awt.Label.CENTER);
        La_login.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        La_login.setForeground(new java.awt.Color(60, 60, 60));
        La_login.setMinimumSize(new java.awt.Dimension(150, 150));
        La_login.setText("Login");
        jToolBar1.add(La_login);

        B_login.setLabel("Login");
        B_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_loginActionPerformed(evt);
            }
        });

        Registra.setForeground(new java.awt.Color(0, 51, 204));
        Registra.setText("Registra-se");

        Esqueci_Senha.setForeground(new java.awt.Color(0, 51, 204));
        Esqueci_Senha.setText("Esqueci a Senha");

        javax.swing.GroupLayout PaLoginLayout = new javax.swing.GroupLayout(PaLogin);
        PaLogin.setLayout(PaLoginLayout);
        PaLoginLayout.setHorizontalGroup(
            PaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PaLoginLayout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addGroup(PaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PaLoginLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(LL_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PaLoginLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(Senha, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PaLoginLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(B_login, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(PaLoginLayout.createSequentialGroup()
                            .addComponent(Esqueci_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Registra, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(TL_Usuario, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(LL_Senha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(194, Short.MAX_VALUE))
        );
        PaLoginLayout.setVerticalGroup(
            PaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaLoginLayout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(LL_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TL_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Senha, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LL_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(B_login, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Esqueci_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Registra, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PaLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PaLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TL_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TL_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TL_UsuarioActionPerformed

    private void B_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_loginActionPerformed
    

    }//GEN-LAST:event_B_loginActionPerformed


       
    
   
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button B_login;
    private javax.swing.JLabel Esqueci_Senha;
    private javax.swing.JPasswordField LL_Senha;
    private java.awt.Label LL_Usuario;
    private java.awt.Label La_login;
    private javax.swing.JPanel PaLogin;
    private javax.swing.JLabel Registra;
    private java.awt.Label Senha;
    private javax.swing.JTextField TL_Usuario;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}

