package interface_bd.Registro;

import java.awt.Dimension;
import interface_bd.Login.Login;
import javax.swing.JOptionPane;
import java.awt.event.ActionListener;
import interface_bd.Api.ApiService; // Importação necessária
import interface_bd.Api.ApiService.RegisterResponse; // Importação da classe de resposta
import java.io.IOException; // Para IOException


/**
 *
 * @author Usuario
 */
public class Registro extends javax.swing.JFrame {

     private static Registro instance;
    private Dimension minimumSize;
    private Dimension preferredSize;


      private Registro() {
        initComponents();
        this.setLocationRelativeTo(null); 
    }

    
    public static Registro getInstance() {
        if (instance == null) {
            instance = new Registro();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PaRegistro = new javax.swing.JPanel();
        RT_Senha = new javax.swing.JPasswordField();
        RR_Usuario = new javax.swing.JTextField();
        RL_Usuario = new java.awt.Label();
        RL_Senha = new java.awt.Label();
        jToolBar1 = new javax.swing.JToolBar();
        L_Registro = new java.awt.Label();
        B_registro = new java.awt.Button();
        R_Confimar_senha = new javax.swing.JPasswordField();
        Confirmar_senha = new java.awt.Label();
        R_Voltar = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro");
        setMinimumSize(this.preferredSize);
        setResizable(false);

        PaRegistro.setBackground(new java.awt.Color(220, 220, 220));
        PaRegistro.setForeground(new java.awt.Color(0, 0, 0));
        PaRegistro.setMaximumSize(this.minimumSize);
        PaRegistro.setMinimumSize(this.preferredSize);
        PaRegistro.setPreferredSize(new java.awt.Dimension(280, 270));

        RT_Senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RT_SenhaActionPerformed(evt);
            }
        });

        RR_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RR_UsuarioActionPerformed(evt);
            }
        });

        RL_Usuario.setAlignment(java.awt.Label.CENTER);
        RL_Usuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        RL_Usuario.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        RL_Usuario.setText("Usuario");

        RL_Senha.setAlignment(java.awt.Label.CENTER);
        RL_Senha.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        RL_Senha.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        RL_Senha.setText("Senha");

        jToolBar1.setBackground(new java.awt.Color(210, 210, 210));
        jToolBar1.setRollover(true);

        L_Registro.setAlignment(java.awt.Label.CENTER);
        L_Registro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        L_Registro.setForeground(new java.awt.Color(60, 60, 60));
        L_Registro.setMinimumSize(new java.awt.Dimension(100, 100));
        L_Registro.setName("Registro"); // NOI18N
        L_Registro.setText("Registro");
        jToolBar1.add(L_Registro);

        B_registro.setActionCommand("Registrar");
        B_registro.setLabel("Registrar");
        B_registro.setName("Registrar"); // NOI18N
        B_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_registroActionPerformed(evt);
            }
        });

        R_Confimar_senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R_Confimar_senhaActionPerformed(evt);
            }
        });

        Confirmar_senha.setAlignment(java.awt.Label.CENTER);
        Confirmar_senha.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Confirmar_senha.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Confirmar_senha.setText("Confirmar Senha");

        R_Voltar.setActionCommand("Registrar");
        R_Voltar.setLabel("Voltar");
        R_Voltar.setName("Voltar"); // NOI18N
        R_Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R_VoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PaRegistroLayout = new javax.swing.GroupLayout(PaRegistro);
        PaRegistro.setLayout(PaRegistroLayout);
        PaRegistroLayout.setHorizontalGroup(
            PaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PaRegistroLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(PaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RL_Usuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RL_Senha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Confirmar_senha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(R_Confimar_senha, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(RT_Senha, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(RR_Usuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
            .addGroup(PaRegistroLayout.createSequentialGroup()
                .addComponent(R_Voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(B_registro, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PaRegistroLayout.setVerticalGroup(
            PaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaRegistroLayout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(PaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B_registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(R_Voltar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(PaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RR_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RL_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(PaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RT_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RL_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(PaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(R_Confimar_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Confirmar_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PaRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PaRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_registroActionPerformed
        String username = RR_Usuario.getText();
        String password = new String(RT_Senha.getPassword());
        String confirmPassword = new String(R_Confimar_senha.getPassword());

        if (username.isEmpty() || password.isEmpty() || confirmPassword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, preencha todos os campos.", "Campos Vazios", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!password.equals(confirmPassword)) {
            JOptionPane.showMessageDialog(this, "As senhas não coincidem.", "Erro de Senha", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Desabilitar o botão para evitar múltiplos cliques
        B_registro.setEnabled(false);

        // Chamar a API em uma nova thread para não travar a UI
        new Thread(() -> {
            try {
                ApiService apiService = ApiService.getInstance();
                RegisterResponse response = apiService.register(username, password);

                // Voltar para a EDT para atualizar a UI
                java.awt.EventQueue.invokeLater(() -> {
                    B_registro.setEnabled(true); // Reabilitar o botão
                    if (response != null && response.getMessage() != null) {
                        JOptionPane.showMessageDialog(this, response.getMessage(), "Registro", JOptionPane.INFORMATION_MESSAGE);
                        if (response.getMessage().contains("registrado com sucesso")) {
                            this.dispose(); // Fecha a tela de registro
                            Login.getInstance().setVisible(true); // Volta para a tela de login
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Resposta vazia ou erro desconhecido.", "Erro de Registro", JOptionPane.ERROR_MESSAGE);
                    }
                });

            } catch (IOException e) {
                e.printStackTrace(); // Imprime o stack trace para depuração
                java.awt.EventQueue.invokeLater(() -> {
                    B_registro.setEnabled(true); // Reabilitar o botão
                    JOptionPane.showMessageDialog(this, "Erro de comunicação com o servidor: " + e.getMessage(), "Erro de Conexão", JOptionPane.ERROR_MESSAGE);
                    // Aqui você pode querer chamar sua tela de ERRO personalizada
                    new interface_bd.Login.ERRO(null, true).setVisible(true); // Usa a classe ERRO existente
                });
            } catch (Exception e) {
                e.printStackTrace(); // Imprime o stack trace para qualquer outra exceção
                java.awt.EventQueue.invokeLater(() -> {
                    B_registro.setEnabled(true); // Reabilitar o botão
                    JOptionPane.showMessageDialog(this, "Ocorreu um erro inesperado: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                    new interface_bd.Login.ERRO(null, true).setVisible(true);
                });
            }
        }).start();

    }//GEN-LAST:event_B_registroActionPerformed

    private void RT_SenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RT_SenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RT_SenhaActionPerformed

    private void RR_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RR_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RR_UsuarioActionPerformed

    private void R_Confimar_senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R_Confimar_senhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R_Confimar_senhaActionPerformed

    private void R_VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R_VoltarActionPerformed
        this.dispose(); // Fecha a tela de registro
        Login.getInstance().setVisible(true); // Mostra a tela de login
    }//GEN-LAST:event_R_VoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Registro.getInstance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button B_registro;
    private java.awt.Label Confirmar_senha;
    private java.awt.Label L_Registro;
    private javax.swing.JPanel PaRegistro;
    private javax.swing.JPasswordField R_Confimar_senha;
    private java.awt.Button R_Voltar;
    private java.awt.Label RL_Senha;
    private java.awt.Label RL_Usuario;
    private javax.swing.JTextField RR_Usuario;
    private javax.swing.JPasswordField RT_Senha;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}