/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interface_bd.ADMIN;


import java.awt.Dimension;
import static java.lang.constant.ConstantDescs.NULL;
import interface_bd.Login.Login; 
import interface_bd.Usuario.Usuario;



/**
 *
 * @author Usuario
 */
public class ADMIN extends javax.swing.JFrame {

    private Dimension minimumSize;
    private Dimension preferredSize;

    private static ADMIN instance;
    /**
     * Creates new form Login
     */
    private ADMIN() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        // pode popular o CB_Admin com usuários do MongoDB aqui ou em metodo separado
    }
    
        public static ADMIN getInstance() {
        if (instance == null) {
            instance = new ADMIN();
        }
        return instance;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PaADMIN = new javax.swing.JPanel();
        A_barra = new javax.swing.JToolBar();
        A_admin = new java.awt.Label();
        A_Sair = new java.awt.Button();
        CB_Admin = new javax.swing.JComboBox<>();
        A_ENTRA_USUARIO = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADMIN");
        setBackground(new java.awt.Color(220, 220, 220));
        setMinimumSize(this.preferredSize);
        setResizable(false);

        PaADMIN.setBackground(new java.awt.Color(220, 220, 220));
        PaADMIN.setForeground(new java.awt.Color(0, 0, 0));
        PaADMIN.setMaximumSize(this.minimumSize);
        PaADMIN.setMinimumSize(this.preferredSize);

        A_barra.setBackground(new java.awt.Color(210, 210, 210));
        A_barra.setRollover(true);

        A_admin.setAlignment(java.awt.Label.CENTER);
        A_admin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        A_admin.setForeground(new java.awt.Color(60, 60, 60));
        A_admin.setMinimumSize(new java.awt.Dimension(100, 100));
        A_admin.setName("Livros"); // NOI18N
        A_admin.setText("ADMIN");
        A_barra.add(A_admin);

        A_Sair.setActionCommand("Sair");
        A_Sair.setLabel("Sair");
        A_Sair.setName("Sair"); // NOI18N
        A_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_SairActionPerformed(evt);
            }
        });

        CB_Admin.setMaximumRowCount(3);
        CB_Admin.setPrototypeDisplayValue(("Matheus Alves do Santos"));

        A_ENTRA_USUARIO.setActionCommand("Sair");
        A_ENTRA_USUARIO.setLabel("Entra no Usuario");
        A_ENTRA_USUARIO.setName("Sair"); // NOI18N
        A_ENTRA_USUARIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_ENTRA_USUARIOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PaADMINLayout = new javax.swing.GroupLayout(PaADMIN);
        PaADMIN.setLayout(PaADMINLayout);
        PaADMINLayout.setHorizontalGroup(
            PaADMINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(A_barra, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
            .addGroup(PaADMINLayout.createSequentialGroup()
                .addGroup(PaADMINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(A_Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PaADMINLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(PaADMINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(A_ENTRA_USUARIO, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CB_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PaADMINLayout.setVerticalGroup(
            PaADMINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaADMINLayout.createSequentialGroup()
                .addComponent(A_barra, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(A_Sair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CB_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(A_ENTRA_USUARIO, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PaADMIN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PaADMIN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void A_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_SairActionPerformed
                this.dispose();
        Login.getInstance().setVisible(true);
    }//GEN-LAST:event_A_SairActionPerformed

    private void A_ENTRA_USUARIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_ENTRA_USUARIOActionPerformed
         this.dispose(); 
        Usuario.getInstance().setVisible(true);
    }//GEN-LAST:event_A_ENTRA_USUARIOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 ADMIN.getInstance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button A_ENTRA_USUARIO;
    private java.awt.Button A_Sair;
    private java.awt.Label A_admin;
    private javax.swing.JToolBar A_barra;
    private javax.swing.JComboBox<String> CB_Admin;
    private javax.swing.JPanel PaADMIN;
    // End of variables declaration//GEN-END:variables
}
